In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split


file_path = r"C:\Users\Abhishek\Downloads\Dataset - Form responses 1 (4).csv"
df = pd.read_csv(file_path)


print("Original Data:")
print(df.head())


df['ROLL NUMBER'] = pd.to_numeric(df['ROLL NUMBER'], errors='coerce')
df['MARKS'] = pd.to_numeric(df['MARKS'], errors='coerce')
df['STIPENED'] = pd.to_numeric(df['STIPENED'], errors='coerce')


df['MARKS'].fillna(df['MARKS'].mean(), inplace=True)


df['ROLL NUMBER'].fillna(0, inplace=True)


df['GENDER'].fillna('UNKNOWN', inplace=True)


print("Cleaned Data:")
print(df.head())


train, test = train_test_split(df, test_size=0.2, random_state=42)


print("Training Data:")
print(train.head())
print("Testing Data:")
print(test.head())

Original Data:
            NAME  ROLL NUMBER SECTION  DEPARTMENT  GENDER   MARKS  STIPENED
0            NaN   12237110.0      NaN         MBA   MALE    25.0      1000
1          Sagar    1222124.0        C         BBA   MALE    66.0      2000
2  Sheikh Faisal    1222141.0        C         BBA   MALE  1000.0      1500
3        Shiwani   12237108.0        B         MBA   MALE     NaN      1600
4          Mehak          NaN       4B         BBA   MALE    33.0      2500
Cleaned Data:
            NAME  ROLL NUMBER SECTION  DEPARTMENT  GENDER        MARKS  \
0            NaN   12237110.0      NaN         MBA   MALE    25.000000
1          Sagar    1222124.0        C         BBA   MALE    66.000000
2  Sheikh Faisal    1222141.0        C         BBA   MALE  1000.000000
3        Shiwani   12237108.0        B         MBA   MALE   182.789474
4          Mehak          0.0       4B         BBA   MALE    33.000000

   STIPENED
0      1000
1      2000
2      1500
3      1600
4      2500
Training Data:
              NAME  ROLL NUMBER SECTION  DEPARTMENT    GENDER        MARKS  \
12  Chandan Kumar    12237243.0        D         NaN  UNKNOWN    99.000000
1            Sagar    1222124.0        C         BBA     MALE    66.000000
13   Sheikh Faisal    1222141.0        C         BBA     MALE  1000.000000
5        Aman Raj           0.0        C         BBA   FEMALE   182.789474
2    Sheikh Faisal    1222141.0        C         BBA     MALE  1000.000000

    STIPENED
12     35000
1       2000
13      1500
5      20000
2       1500
Testing Data:
             NAME  ROLL NUMBER SECTION  DEPARTMENT    GENDER       MARKS  \
15   Tanu kumari     1222074.0        B         BBA  UNKNOWN  111.000000
9           ADITI    1222370.0        B         BBA  UNKNOWN   56.000000
0             NaN   12237110.0      NaN         MBA     MALE   25.000000
8   Prabhjot kaur    1222097.0        B         BBA     MALE  182.789474
17         Himani   11222565.0        B         LLB   FEMALE   45.000000

    STIPENED
15     30000
9       1900
0       1000
8       2600
17       785

C:\Users\Abhishek\AppData\Local\Temp\ipykernel_10920\4099872224.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['MARKS'].fillna(df['MARKS'].mean(), inplace=True)
C:\Users\Abhishek\AppData\Local\Temp\ipykernel_10920\4099872224.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ROLL NUMBER'].fillna(0, inplace=True)
C:\Users\Abhishek\AppData\Local\Temp\ipykernel_10920\4099872224.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['GENDER'].fillna('UNKNOWN', inplace=True)